### ISSUE TITLE
Duplicate entry 'theme:typecho-theme-material-mas-0' for key 'PRIMARY'

### ISSUE THREAD

**Issue by huanghu996** [viosey/typecho-theme-material#89]
exception 'Typecho_Db_Query_Exception' with message 'Duplicate entry 'theme:typecho-theme-material-mas-0' for key 'PRIMARY'' in D:\localuser\ftp6189698\Web\var\Typecho\Db\Adapter\Mysql.php:88
Stack trace:
#0 D:\localuser\ftp6189698\Web\var\Typecho\Db.php(354): Typecho_Db_Adapter_Mysql->query('INSERT INTO typ...', Resource id #29, 2, 'INSERT')
#1 D:\localuser\ftp6189698\Web\var\Widget\Abstract\Options.php(56): Typecho_Db->query(Object(Typecho_Db_Query))
#2 D:\localuser\ftp6189698\Web\var\Widget\Themes\Edit.php(130): Widget_Abstract_Options->insert(Array)
#3 D:\localuser\ftp6189698\Web\var\Widget\Themes\Edit.php(176): Widget_Themes_Edit->config('typecho-theme-m...')
#4 D:\localuser\ftp6189698\Web\var\Widget\Do.php(82): Widget_Themes_Edit->action()
#5 D:\localuser\ftp6189698\Web\var\Typecho\Widget.php(221): Widget_Do->execute()
#6 D:\localuser\ftp6189698\Web\var\Typecho\Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#7 D:\localuser\ftp6189698\Web\index.php(23): Typecho_Router::dispatch()
#8 {main}

**Comment by BluesFu** [comment]
你把主题名字改成material就可以了，我就是这样解决的

**Comment by BluesFu** [comment]
rename the theme to “material”。。。all is ok。。you can just have a try .this is really a nice theme.
